# Generated by Django 3.1.4 on 2020-12-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0002_auto_20201216_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cpf',
            field=models.IntegerField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default=2, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
