# Generated by Django 3.1.4 on 2020-12-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0004_auto_20201216_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
