# Generated by Django 3.1.4 on 2020-12-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0005_auto_20201216_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Debito'), ('C', 'Credito')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conta', to='app_banco.conta')),
            ],
        ),
    ]
