# Generated by Django 3.1.4 on 2020-12-16 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0006_conta_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='cliente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='app_banco.customuser'),
            preserve_default=False,
        ),
    ]
